skip frames up to actual seek timestamp in symphonia decoder
RustyDAW/rt-audio-disk-stream pull request #52
Opened 2024-09-28 14:44 UTC by edwloef

This seems, to me, to fix #43.

What I'm doing is saving the difference between the requested and actual seek timestamps, and skipping decoded packets until the requested seek timestamp is within the decoded packet. I then push the index inside the decoded buffer forwards to account for the offset of the requested seek timestamp within the packet.

In my testing this gets rid of the audio artifacts that result from seeking in mp3 files.

2025-01-16 16:08 UTC, edwloef commented
@uklotzde sorry for the ping but this has been open for a while and is a blocker for me actually using this crate, could you have a look please?

2025-01-19 21:26 UTC, uklotzde reviewed
Sorry for the delay. I was not aware that I am in charge of reviewing PRs of this repo.

Not sure if I am able to finally merge this PR after approval. We'll see.

2025-01-19 21:26 UTC, uklotzde commented on decode_symphonia/src/lib.rs
> +                self.seek_diff = (res.required_ts - res.actual_ts) as usize;
At least a debug assertions should verify that the assumption `actual <= required` is valid. It only works for `SeekMode::Accurate` which should probably be mentioned here.

2025-01-19 21:27 UTC, uklotzde commented
I recommend that you work on separate feature branches in your fork and only use `main` for tracking upstream.

2025-01-19 22:15 UTC, edwloef commented
> I was not aware that I am in charge of reviewing PRs of this repo.

I'm not sure whether you are, but you seem to be the only collaborator who I can see is active on GitHub 😅 I'm very sorry if you aren't, hope this isn't too much of a hassle.

> I recommend that you work on separate feature branches in your fork and only use main for tracking upstream.

Ah oops seems like I forgot to switch branches lol. Should I fix and reopen this?

2025-01-20 00:23 UTC, uklotzde commented
> Ah oops seems like I forgot to switch branches lol. Should I fix and reopen this?

Not needed. Just a recommendation for future work.

2025-01-20 00:24 UTC, uklotzde approved these changes

2025-01-20 09:13 UTC, uklotzde requested changes
I'll try to fix the unrelated pre-commit issues separately. But the tests need to pass before merging.

2025-01-20 09:24 UTC, edwloef commented
I'll look into the `decode_symphonia` tests. The old tests were made under the assumption of the wrong Symphonia seeking behavior, I'll probably just need to update some numbers here and there.

2025-01-20 10:12 UTC, uklotzde commented
#53 fixes the pre-commit issues. Someone has to approve this PR.

2025-01-20 11:30 UTC, orottier commented
I have merged #53 but I can't rebase the remote branch of this PR. @edwloef could you pick up the latest changes from the main branch and push?

2025-01-20 11:39 UTC, orottier approved these changes

2025-01-20 11:41 UTC, orottier commented
I can't merge with your 'requested changes' @uklotzde, could you please approve again?
When that is done I can publish a new package version, at least, I think I am the crate admin

2025-01-20 11:43 UTC, uklotzde approved these changes

2025-01-20 11:44 UTC, merged

2025-01-21 07:27 UTC, orottier commented
Released in decode_symphonia v0.3.2.
The main crate does not need updating, it should pick it up after running cargo update
Thanks @edwloef